export const Teeth = [
    {
        adulto: "TeethAdulto",
        teeth: [
            {
                name: "Muela Superior",
                number: 18,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 17,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 16,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 15,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 14,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 13,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 12,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 11,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 21,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 22,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 23,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 24,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 25,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 26,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 27,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 28,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 41,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 42,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 43,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 44,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 45,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 46,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 47,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 48,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 31,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 32,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 33,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 34,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 35,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 36,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 37,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 38,
                image: "",
                selected: false,
                visible: true,
            }
        ]
    },
    {
        niño: "TeethNiño",
        teeth: [
            {
                name: "Muela Superior",
                number: 51,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 52,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 53,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 54,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 55,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 61,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 62,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 63,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 64,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 65,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 81,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 82,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 83,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 84,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 85,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 71,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 72,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 73,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 74,
                image: "",
                selected: false,
                visible: true,
            },
            {
                name: "Muela Superior",
                number: 75,
                image: "",
                selected: false,
                visible: true,
            }
        ]
    },
]