export const accountInputs = [
	{
		name: "Correo",
		register: "correo",
		value: "",
		min: 12,
		max: 100,
		visible: false,
		required: true,
		pattern: { value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/, message: "Formato de email incorrecto." },
	},
	{
		name: "Telefono",
		register: "telefono",
		value: "",
		type: "number",
		min: 10,
		max: 10,
		visible: false,
		required: true,
	},
	{
		name: "Wallet",
		register: "wallet",
		value: "",
		min: 10,
		max: 100,
		visible: true,
		required: true,
	},
	{
		name: "Cuenta CLABE",
		register: "clabe",
		value: "",
		min: 18,
		max: 18,
		visible: false,
		required: true,
	},
	{
		name: "Numero de Tarjeta",
		register: "tarjeta",
		value: "",
		min: 16,
		max: 16,
		visible: false,
		required: true,
	},
]